---
# tasks file for rpi-noobs-recovery
- name: Mount noobs partition
  mount:
    path: "{{ rpi_mount_path }}"
    src: "{{ noobs_partition }}"
    fstype: vfat
    state: mounted
    boot: no
  tags: notest

- name: Get Latest Release Date information from repository for OS {{ requested_os_name }}
  block:
    - name: Get Information for Requested OS from defined repository
      include_tasks: os_get_remote_info.yml
      # this fill the requested_os_description variable
    - name: Get Release data available from os description
      set_fact:
        requested_os_release_date: "{{ requested_os_description.release_date }}"
  when: requested_os_release_date == "latest"

- name: Check/Clean OS local package(s)
  include_tasks: os_check.yml
  # this fill the local_package_description variable, if local package found

- name: Download OS package if needed
  block:
    - name: Get Information for Requested OS (if not already done)
      include_tasks: os_get_remote_info.yml
      when: requested_os_description is not defined
    - name: Download OS
      include_tasks: os_download.yml
  when: local_package_description is not defined

- name: Force ssh on raspos reboot
  copy:
    content: ""
    dest: "{{ raspos_ssh_file_path }}"

- name: Update NOOBS command line to force install
  include_tasks: cmdline_add_option.yml
  loop: "{{ noobs_cmdline_to_add }}"

- name: Reboot to start NOOBS auto install
  reboot:
    reboot_timeout: 3600
  tags: notest
