---
# tasks file to download the os package described by the variable 
# requested_os_description
# similar to noob method on_actionWrite_image_to_disk_triggered
# (https://github.com/raspberrypi/noobs/blob/00822079b514e5db9dbd6e0e3c86628b94b4fa9a/recovery/mainwindow.cpp#L586)
# followed by startImageWrite method
# (https://github.com/raspberrypi/noobs/blob/00822079b514e5db9dbd6e0e3c86628b94b4fa9a/recovery/mainwindow.cpp#L1537)
#
# The requested_os_description contains one json entry from an os_list global file.

- name: Create OS Destination Directory Name
  set_fact:
    requested_os_dest: "{{ noobs_os_dir_path }}/{{ requested_os_description.os_name | replace(' ','_') }}"

- name: Create OS Destination Directory
  file:
    path: "{{ requested_os_dest }}"
    state: directory

- name: Download all mandatory artifacts and optional one that are defined
  get_url:
    url: "{{ requested_os_description[item.attribute] }}"
    dest: "{{ requested_os_dest }}/{{ item.dest }}"
  when: (item.mandatory) or (requested_os_description[item.attribute] is defined)
  with_items: "{{ noobs_att_download_dest }}"

- name: Extract/Delete Marketing tarball with slides (if needed)
  block:
    - name: Install tar utility
      package:
        name: tar
        state: present
    - name: Extract Marketing tarball
      unarchive:
        src: "{{ requested_os_dest }}/{{ noobs_att_dest_marketing_tar_file }}"
        dest: "{{ requested_os_dest }}"
        remote_src: yes
    - name: Delete Marketing tarball
      file:
        path: "{{ requested_os_dest }}/{{ noobs_att_dest_marketing_tar_file }}"
        state: absent
  when: requested_os_description[noobs_att_prop_marketing] is defined

# TODO: try to Insert tarball download URL information into partition_info.json ? (and not download them ?) (OPTION FOR THAT ?)
# as here https://github.com/raspberrypi/noobs/blob/00822079b514e5db9dbd6e0e3c86628b94b4fa9a/recovery/mainwindow.cpp#L1567
# i don't know if it is ok for a os in /os dir.. in the link this is a download os in /settings/os/
# should be: https://github.com/raspberrypi/noobs/blob/00822079b514e5db9dbd6e0e3c86628b94b4fa9a/recovery/multiimagewritethread.cpp#L449
- name: Download partition tarballs
  get_url:
    url: "{{ item }}"
    dest: "{{ requested_os_dest }}/{{ item | basename }}"
  with_items: "{{ requested_os_description[noobs_att_prop_tarballs] }}"
